#!/bin/bash

# CVCC Notification Testing - Quick Reference Commands
# Run these commands from the backend directory (cd backend)

echo "🧪 CVCC Notification Testing Quick Reference"
echo "=============================================="
echo ""
echo "Make sure backend is running: pnpm run start:dev"
echo ""
echo "📧 EMAIL TESTS:"
echo ""
echo "1. Welcome Email"
echo "   npx ts-node scripts/test-notifications.ts --channel email --recipient user@example.com --template welcome"
echo ""
echo "2. Password Reset Email"
echo "   npx ts-node scripts/test-notifications.ts --channel email --recipient user@example.com --template password-reset"
echo ""
echo "3. Vaccination Reminder Email"
echo "   npx ts-node scripts/test-notifications.ts --channel email --recipient user@example.com --template reminder"
echo ""
echo "4. Custom Email"
echo "   npx ts-node scripts/test-notifications.ts --channel email --recipient user@example.com --template custom --subject 'Your Subject' --html '<p>Your HTML content</p>'"
echo ""
echo "📱 SMS TESTS:"
echo ""
echo "5. SMS Vaccination Reminder"
echo "   npx ts-node scripts/test-notifications.ts --channel sms --recipient +233501234567 --template reminder"
echo ""
echo "6. SMS Appointment Notification"
echo "   npx ts-node scripts/test-notifications.ts --channel sms --recipient +233501234567 --template appointment"
echo ""
echo "🔀 COMBINED TESTS:"
echo ""
echo "7. Both Email & SMS (Reminder)"
echo "   npx ts-node scripts/test-notifications.ts --channel both --recipient user@example.com --template reminder"
echo ""
echo "✅ Quick Test (All in one)"
echo "   ./scripts/quick-test-notifications.sh"
echo ""
echo "Help:"
echo "   npx ts-node scripts/test-notifications.ts --help"
echo ""
