export const GHANA_REGIONS = [
  "Ahafo",
  "Ashanti",
  "Bono",
  "Bono East",
  "Central",
  "Eastern",
  "Greater Accra",
  "North East",
  "Northern",
  "Oti",
  "Savannah",
  "Upper East",
  "Upper West",
  "Volta",
  "Western",
  "Western North",
] as const;

export type GhanaRegion = (typeof GHANA_REGIONS)[number];

export const GREATER_ACCRA_DISTRICTS = [
  "Ablekuma Central Municipal",
  "Ablekuma North Municipal",
  "Ablekuma West Municipal",
  "Accra Metropolitan",
  "Adentan Municipal",
  "Ashaiman Municipal",
  "Ayawaso Central Municipal",
  "Ayawaso East Municipal",
  "Ayawaso North Municipal",
  "Ayawaso West Municipal",
  "Ga Central Municipal",
  "Ga East Municipal",
  "Ga North Municipal",
  "Ga South Municipal",
  "Ga West Municipal",
  "Korle Klottey Municipal",
  "Kpone-Katamanso Municipal",
  "La Dade Kotopon Municipal",
  "La Nkwantanang-Madina Municipal",
  "Ledzokuku Municipal",
  "Ningo-Prampram District",
  "Okaikwei North Municipal",
  "Shai Osudoku District",
  "Tema Metropolitan",
  "Tema West Municipal",
] as const;

export type GreaterAccraDistrict = (typeof GREATER_ACCRA_DISTRICTS)[number];
